### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by I-Am-The-Great** [I-Am-The-Great/BombSquadServerLinux64bit1.4.145Modified#1]
Write in this how do you like this repository.

**Comment by iotzeep** [comment]
I can't see any characters in the map, could you help me?
![s](https://user-images.githubusercontent.com/33192979/46824744-6b2a0480-cdc4-11e8-91bf-f0a8530bfb25.jpg)

**Comment by iotzeep** [comment]
thank you , I use them on my server named IotZengP

**Comment by I-Am-The-Great** [comment]
Good, I am happy to know that someone use these files.

**Comment by iotzeep** [comment]
> Good, I am happy to know that someone use these files.

Today my server has encountered several problems. First of all, it has a problem now. I can see the game interface and all the bombs, but I can't see myself. I attached my log file at the end. Second, I have no way to change the 10 texts displayed in the game. After I modified bsMap.py, it still shows the previous content. I want to ask if I want to change those texts. Is there a more detailed readme file that tells me how to modify it. Third, can you share a classic PlayList code? Finally, thank you for sharing all the content here.
my Server ip address:47.107.32.79 port:43211 

[server.log](https://github.com/I-Am-The-Great/BombSquadServerLinux64bit1.4.145Modified/files/2471644/server.log)

**Comment by I-Am-The-Great** [comment]
hmm.. have you edited the files , if yes maybe that caused an error

**Comment by I-Am-The-Great** [comment]
you have to edit in bsMap.py in every map to get your desired texts

**Comment by I-Am-The-Great** [comment]
listen i added 1 line whose source i deleted in abhinayServerTools.py , that caused error , sorry

**Comment by I-Am-The-Great** [comment]
> > Good, I am happy to know that someone use these files.
> 
> Today my server has encountered several problems. First of all, it has a problem now. I can see the game interface and all the bombs, but I can't see myself. I attached my log file at the end. Second, I have no way to change the 10 texts displayed in the game. After I modified bsMap.py, it still shows the previous content. I want to ask if I want to change those texts. Is there a more detailed readme file that tells me how to modify it. Third, can you share a classic PlayList code? Finally, thank you for sharing all the content here.
> my Server ip address:47.107.32.79 port:43211
> 
> [server.log](https://github.com/I-Am-The-Great/BombSquadServerLinux64bit1.4.145Modified/files/2471644/server.log)

i think you should not share ip and port in public, you should have email it to me

**Comment by iotzeep** [comment]
> listen i added 1 line whose source i deleted in abhinayServerTools.py , that caused error , sorry

I reunzip server files and only modified the config.py and getPermissionsHashs.py .But the situation is the same as before

**Comment by iotzeep** [comment]
> > > Good, I am happy to know that someone use these files.
> > 
> > 
> > Today my server has encountered several problems. First of all, it has a problem now. I can see the game interface and all the bombs, but I can't see myself. I attached my log file at the end. Second, I have no way to change the 10 texts displayed in the game. After I modified bsMap.py, it still shows the previous content. I want to ask if I want to change those texts. Is there a more detailed readme file that tells me how to modify it. Third, can you share a classic PlayList code? Finally, thank you for sharing all the content here.
> > my Server ip address:47.107.32.79 port:43211
> > [server.log](https://github.com/I-Am-The-Great/BombSquadServerLinux64bit1.4.145Modified/files/2471644/server.log)
> 
> i think you should not share ip and port in public, you should have email it to me

I'll delete the message after solve it

**Comment by I-Am-The-Great** [comment]
download the files now, i corrected

**Comment by I-Am-The-Great** [comment]
> > listen i added 1 line whose source i deleted in abhinayServerTools.py , that caused error , sorry
> 
> I reunzip server files and only modified the config.py and getPermissionsHashs.py .But the situation is the same as before

don.t change config.py it is a base file of your server.

**Comment by I-Am-The-Great** [comment]
download the latest now, i commited just few minutes ago

**Comment by TheDevXen** [comment]
@I-Am-The-Great Hey

**Comment by I-Am-The-Great** [comment]
hi

**Comment by TheDevXen** [comment]
@I-Am-The-Great 😕😐😐😒😒😒

**Comment by I-Am-The-Great** [comment]
what are you saying?

**Comment by p4y4** [comment]
The main problem has been resolved. But there are still minor issues :(

**Comment by I-Am-The-Great** [comment]
@p4y4 Really?

**Comment by I-Am-The-Great** [comment]
which which

**Comment by p4y4** [comment]
w8

**Comment by p4y4** [comment]
[serverlog.txt](https://github.com/I-Am-The-Great/BombSquadServerLinux64bit1.4.145Modified/files/2471737/serverlog.txt)
Why do you get these?

**Comment by iotzeep** [comment]
I have suceed, but I disconnected from Internet just now. Thanks for everything.

**Comment by I-Am-The-Great** [comment]
> 
> 
> [serverlog.txt](https://github.com/I-Am-The-Great/BombSquadServerLinux64bit1.4.145Modified/files/2471737/serverlog.txt)
> Why do you get these?

well, those are just minor lines that don't affect the gameplay much.
